// Catálogo curado de iconos de HugeIcons (free) usados en Karto.
// Import selectivo: solo lo que usamos entra al bundle.
import {
  Folder01Icon,
  WorkflowSquare01Icon,
  ViewIcon,
  ViewOffSlashIcon,
  Copy01Icon,
  PlusSignIcon,
  Search01Icon,
  Cancel01Icon,
  CancelSquareIcon,
  SquareLock01Icon,
  Key01Icon,
  Logout01Icon,
  MoreHorizontalIcon,
  Delete02Icon,
  Edit02Icon,
  Link01Icon,
  ComputerTerminal01Icon,
  ConnectIcon,
  ArrowRight01Icon,
  LayoutLeftIcon,
  Settings01Icon,
  SourceCodeSquareIcon,
  Location01Icon,
  Note01Icon,
  CommandLineIcon,
  FloppyDiskIcon,
  ArrowExpandIcon,
  ArrowShrinkIcon,
  Coffee02Icon,
  Bug01Icon,
  LicenseIcon,
} from "@hugeicons/core-free-icons";
import type { IconSvgElement } from "@hugeicons/svelte";

/** Iconos semánticos de UI. */
export const icons = {
  folder: Folder01Icon,
  diagram: WorkflowSquare01Icon,
  eye: ViewIcon,
  eyeOff: ViewOffSlashIcon,
  copy: Copy01Icon,
  add: PlusSignIcon,
  search: Search01Icon,
  close: Cancel01Icon,
  closeSquare: CancelSquareIcon,
  lock: SquareLock01Icon,
  key: Key01Icon,
  logout: Logout01Icon,
  more: MoreHorizontalIcon,
  delete: Delete02Icon,
  edit: Edit02Icon,
  link: Link01Icon,
  terminal: ComputerTerminal01Icon,
  connect: ConnectIcon,
  chevron: ArrowRight01Icon,
  sidebar: LayoutLeftIcon,
  settings: Settings01Icon,
  script: SourceCodeSquareIcon,
  address: Location01Icon,
  notes: Note01Icon,
  commandLine: CommandLineIcon,
  save: FloppyDiskIcon,
  expand: ArrowExpandIcon,
  minimize: ArrowShrinkIcon,
  coffee: Coffee02Icon,
  bug: Bug01Icon,
  license: LicenseIcon,
} satisfies Record<string, IconSvgElement>;
